services:
  empresa:
    build: ./empresa
    container_name: empresa
    ports:
      - "8090:8080"
    networks:
      - red_combustible

  distribuidor:
    build: ./distribuidor
    container_name: distribuidor
    networks:
      - red_combustible
    depends_on:
      - empresa

  surtidor93:
    build: ./surtidor
    container_name: surtidor93
    environment:
      - SURTIDOR_ID=s93
      - TIPO_COMBUSTIBLE=93
    networks:
      - red_combustible
    depends_on:
      - distribuidor

  surtidor95:
    build: ./surtidor
    container_name: surtidor95
    environment:
      - SURTIDOR_ID=s95
      - TIPO_COMBUSTIBLE=95
    networks:
      - red_combustible
    depends_on:
      - distribuidor

  surtidor97:
    build: ./surtidor
    container_name: surtidor97
    environment:
      - SURTIDOR_ID=s97
      - TIPO_COMBUSTIBLE=97
    networks:
      - red_combustible
    depends_on:
      - distribuidor

  surtidordiesel:
    build: ./surtidor
    container_name: surtidordiesel
    environment:
      - SURTIDOR_ID=sdie
      - TIPO_COMBUSTIBLE=diesel
    networks:
      - red_combustible
    depends_on:
      - distribuidor

  surtidorkerosene:
    build: ./surtidor
    container_name: surtidorkerosene
    environment:
      - SURTIDOR_ID=sker
      - TIPO_COMBUSTIBLE=kerosene
    networks:
      - red_combustible
    depends_on:
      - distribuidor

networks:
  red_combustible:
    driver: bridge
